### ISSUE TITLE
Custom KDE theme causes pipecontrol to SEGV

### ISSUE THREAD

**Issue by CCF100** [portaloffreedom/pipecontrol#12]
I have [this](https://gitgud.io/wackyideas/aerothemeplasma) KDE Plasma theme installed, and pipecontrol refuses to start with it. All of my other applications have worked fine, so I'm not exactly sure what the problem is. I compiled pipecontrol with LLVM's Address Sanitizer, and here's the stacktrace I got back from it:
```
└❯ pipecontrol
QML debugging is enabled. Only use this in a safe environment.
QFont::fromString: Invalid description 'Segoe UI Variable Static Small,9,-1,5,400,0,0,0,0,0,0,0,0,0,0,1'
QFont::fromString: Invalid description 'Segoe UI Variable Static Small,9,-1,5,400,0,0,0,0,0,0,0,0,0,0,1'
QFont::fromString: Invalid description 'Segoe UI Variable Static Small,9,-1,5,400,0,0,0,0,0,0,0,0,0,0,1'
Compiled with libpipewire  1.2.7
Linked   with libpipewire  1.2.7
Unrecognized pipewire setting " clock.rate " with value " 48000 "
Unrecognized pipewire setting " clock.allowed-rates " with value " [ 48000 ] "
Unrecognized pipewire setting " clock.quantum " with value " 1024 "
AddressSanitizer:DEADLYSIGNAL
=================================================================
==78487==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x7f75cd3130c4 bp 0x7ffee54c5870 sp 0x7ffee54c5770 T0)
==78487==The signal is caused by a READ memory access.
==78487==Hint: address points to the zero page.
    #0 0x7f75cd3130c4  (/usr/lib/qt/qml/org/kde/qqc2desktopstyle/private/libqqc2desktopstyleplugin.so+0xa0c4) (BuildId: a2386eb822f7ba0f4d47b7de56bbf05df60b8f76)
    #1 0x7f75cd315ef6  (/usr/lib/qt/qml/org/kde/qqc2desktopstyle/private/libqqc2desktopstyleplugin.so+0xcef6) (BuildId: a2386eb822f7ba0f4d47b7de56bbf05df60b8f76)
    #2 0x7f75cd3226aa  (/usr/lib/qt/qml/org/kde/qqc2desktopstyle/private/libqqc2desktopstyleplugin.so+0x196aa) (BuildId: a2386eb822f7ba0f4d47b7de56bbf05df60b8f76)
    #3 0x7f75d34423a4  (/usr/lib/libQt5Qml.so.5+0x2423a4) (BuildId: 2bbc5b481c56048f88ef9c08ef8e85a4c34bde07)
    #4 0x7f75d34c945b in QQmlObjectCreator::setPropertyValue(QQmlPropertyData const*, QV4::CompiledData::Binding const*) (/usr/lib/libQt5Qml.so.5+0x2c945b) (BuildId: 2bbc5b481c56048f88ef9c08ef8e85a4c34bde07)
    #5 0x7f75d34cbc5c in QQmlObjectCreator::setPropertyBinding(QQmlPropertyData const*, QV4::CompiledData::Binding const*) (/usr/lib/libQt5Qml.so.5+0x2cbc5c) (BuildId: 2bbc5b481c56048f88ef9c08ef8e85a4c34bde07)
    #6 0x7f75d34cdb34 in QQmlObjectCreator::setupBindings(bool) (/usr/lib/libQt5Qml.so.5+0x2cdb34) (BuildId: 2bbc5b481c56048f88ef9c08ef8e85a4c34bde07)
    #7 0x7f75d34ceb90 in QQmlObjectCreator::populateInstance(int, QObject*, QObject*, QQmlPropertyData const*) (/usr/lib/libQt5Qml.so.5+0x2ceb90) (BuildId: 2bbc5b481c56048f88ef9c08ef8e85a4c34bde07)
    #8 0x7f75d34cac59 in QQmlObjectCreator::createInstance(int, QObject*, bool) (/usr/lib/libQt5Qml.so.5+0x2cac59) (BuildId: 2bbc5b481c56048f88ef9c08ef8e85a4c34bde07)
    #9 0x7f75d34cc0dc in QQmlObjectCreator::setPropertyBinding(QQmlPropertyData const*, QV4::CompiledData::Binding const*) (/usr/lib/libQt5Qml.so.5+0x2cc0dc) (BuildId: 2bbc5b481c56048f88ef9c08ef8e85a4c34bde07)
    #10 0x7f75d34cdb34 in QQmlObjectCreator::setupBindings(bool) (/usr/lib/libQt5Qml.so.5+0x2cdb34) (BuildId: 2bbc5b481c56048f88ef9c08ef8e85a4c34bde07)
    #11 0x7f75d34ceb90 in QQmlObjectCreator::populateInstance(int, QObject*, QObject*, QQmlPropertyData const*) (/usr/lib/libQt5Qml.so.5+0x2ceb90) (BuildId: 2bbc5b481c56048f88ef9c08ef8e85a4c34bde07)
    #12 0x7f75d34cac59 in QQmlObjectCreator::createInstance(int, QObject*, bool) (/usr/lib/libQt5Qml.so.5+0x2cac59) (BuildId: 2bbc5b481c56048f88ef9c08ef8e85a4c34bde07)
    #13 0x7f75d34c6da3 in QQmlObjectCreator::create(int, QObject*, QQmlInstantiationInterrupt*, int) (/usr/lib/libQt5Qml.so.5+0x2c6da3) (BuildId: 2bbc5b481c56048f88ef9c08ef8e85a4c34bde07)
    #14 0x7f75d34ca822 in QQmlObjectCreator::createInstance(int, QObject*, bool) (/usr/lib/libQt5Qml.so.5+0x2ca822) (BuildId: 2bbc5b481c56048f88ef9c08ef8e85a4c34bde07)
    #15 0x7f75d34cc0dc in QQmlObjectCreator::setPropertyBinding(QQmlPropertyData const*, QV4::CompiledData::Binding const*) (/usr/lib/libQt5Qml.so.5+0x2cc0dc) (BuildId: 2bbc5b481c56048f88ef9c08ef8e85a4c34bde07)
    #16 0x7f75d34cdb34 in QQmlObjectCreator::setupBindings(bool) (/usr/lib/libQt5Qml.so.5+0x2cdb34) (BuildId: 2bbc5b481c56048f88ef9c08ef8e85a4c34bde07)
    #17 0x7f75d34ceb90 in QQmlObjectCreator::populateInstance(int, QObject*, QObject*, QQmlPropertyData const*) (/usr/lib/libQt5Qml.so.5+0x2ceb90) (BuildId: 2bbc5b481c56048f88ef9c08ef8e85a4c34bde07)
    #18 0x7f75d34cac59 in QQmlObjectCreator::createInstance(int, QObject*, bool) (/usr/lib/libQt5Qml.so.5+0x2cac59) (BuildId: 2bbc5b481c56048f88ef9c08ef8e85a4c34bde07)
    #19 0x7f75d34cc0dc in QQmlObjectCreator::setPropertyBinding(QQmlPropertyData const*, QV4::CompiledData::Binding const*) (/usr/lib/libQt5Qml.so.5+0x2cc0dc) (BuildId: 2bbc5b481c56048f88ef9c08ef8e85a4c34bde07)
    #20 0x7f75d34cdb34 in QQmlObjectCreator::setupBindings(bool) (/usr/lib/libQt5Qml.so.5+0x2cdb34) (BuildId: 2bbc5b481c56048f88ef9c08ef8e85a4c34bde07)
    #21 0x7f75d34ceb90 in QQmlObjectCreator::populateInstance(int, QObject*, QObject*, QQmlPropertyData const*) (/usr/lib/libQt5Qml.so.5+0x2ceb90) (BuildId: 2bbc5b481c56048f88ef9c08ef8e85a4c34bde07)
    #22 0x7f75d34cac59 in QQmlObjectCreator::createInstance(int, QObject*, bool) (/usr/lib/libQt5Qml.so.5+0x2cac59) (BuildId: 2bbc5b481c56048f88ef9c08ef8e85a4c34bde07)
    #23 0x7f75d34c6da3 in QQmlObjectCreator::create(int, QObject*, QQmlInstantiationInterrupt*, int) (/usr/lib/libQt5Qml.so.5+0x2c6da3) (BuildId: 2bbc5b481c56048f88ef9c08ef8e85a4c34bde07)
    #24 0x7f75d34ca822 in QQmlObjectCreator::createInstance(int, QObject*, bool) (/usr/lib/libQt5Qml.so.5+0x2ca822) (BuildId: 2bbc5b481c56048f88ef9c08ef8e85a4c34bde07)
    #25 0x7f75d34c6da3 in QQmlObjectCreator::create(int, QObject*, QQmlInstantiationInterrupt*, int) (/usr/lib/libQt5Qml.so.5+0x2c6da3) (BuildId: 2bbc5b481c56048f88ef9c08ef8e85a4c34bde07)
    #26 0x7f75d34ca822 in QQmlObjectCreator::createInstance(int, QObject*, bool) (/usr/lib/libQt5Qml.so.5+0x2ca822) (BuildId: 2bbc5b481c56048f88ef9c08ef8e85a4c34bde07)
    #27 0x7f75d34c6da3 in QQmlObjectCreator::create(int, QObject*, QQmlInstantiationInterrupt*, int) (/usr/lib/libQt5Qml.so.5+0x2c6da3) (BuildId: 2bbc5b481c56048f88ef9c08ef8e85a4c34bde07)
    #28 0x7f75d34ca822 in QQmlObjectCreator::createInstance(int, QObject*, bool) (/usr/lib/libQt5Qml.so.5+0x2ca822) (BuildId: 2bbc5b481c56048f88ef9c08ef8e85a4c34bde07)
    #29 0x7f75d34cc0dc in QQmlObjectCreator::setPropertyBinding(QQmlPropertyData const*, QV4::CompiledData::Binding const*) (/usr/lib/libQt5Qml.so.5+0x2cc0dc) (BuildId: 2bbc5b481c56048f88ef9c08ef8e85a4c34bde07)
    #30 0x7f75d34cdb34 in QQmlObjectCreator::setupBindings(bool) (/usr/lib/libQt5Qml.so.5+0x2cdb34) (BuildId: 2bbc5b481c56048f88ef9c08ef8e85a4c34bde07)
    #31 0x7f75d34ceb90 in QQmlObjectCreator::populateInstance(int, QObject*, QObject*, QQmlPropertyData const*) (/usr/lib/libQt5Qml.so.5+0x2ceb90) (BuildId: 2bbc5b481c56048f88ef9c08ef8e85a4c34bde07)
    #32 0x7f75d34cac59 in QQmlObjectCreator::createInstance(int, QObject*, bool) (/usr/lib/libQt5Qml.so.5+0x2cac59) (BuildId: 2bbc5b481c56048f88ef9c08ef8e85a4c34bde07)
    #33 0x7f75d34c6da3 in QQmlObjectCreator::create(int, QObject*, QQmlInstantiationInterrupt*, int) (/usr/lib/libQt5Qml.so.5+0x2c6da3) (BuildId: 2bbc5b481c56048f88ef9c08ef8e85a4c34bde07)
    #34 0x7f75d3452e58 in QQmlComponentPrivate::beginCreate(QQmlContextData*) (/usr/lib/libQt5Qml.so.5+0x252e58) (BuildId: 2bbc5b481c56048f88ef9c08ef8e85a4c34bde07)
    #35 0x7f75d34bdc87 in QQmlApplicationEnginePrivate::finishLoad(QQmlComponent*) (/usr/lib/libQt5Qml.so.5+0x2bdc87) (BuildId: 2bbc5b481c56048f88ef9c08ef8e85a4c34bde07)
    #36 0x7f75d34be2d5 in QQmlApplicationEngine::load(QUrl const&) (/usr/lib/libQt5Qml.so.5+0x2be2d5) (BuildId: 2bbc5b481c56048f88ef9c08ef8e85a4c34bde07)
    #37 0x56547d95d1f4 in main /usr/src/debug/pipecontrol/pipecontrol-0.2.11/src/main.cpp:92
    #38 0x7f75d2634e07  (/usr/lib/libc.so.6+0x25e07) (BuildId: 98b3d8e0b8c534c769cb871c438b4f8f3a8e4bf3)
    #39 0x7f75d2634ecb in __libc_start_main (/usr/lib/libc.so.6+0x25ecb) (BuildId: 98b3d8e0b8c534c769cb871c438b4f8f3a8e4bf3)
    #40 0x56547d95e924 in _start (/usr/bin/pipecontrol+0x12924) (BuildId: 47c264daf62ebce7f10dd8325c4d90c3d37eed7c)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (/usr/lib/qt/qml/org/kde/qqc2desktopstyle/private/libqqc2desktopstyleplugin.so+0xa0c4) (BuildId: a2386eb822f7ba0f4d47b7de56bbf05df60b8f76) 
==78487==ABORTING
```

**Comment by portaloffreedom** [comment]
I've updated to KF6, any chance that fixed it?
